FROM nginx:latest

LABEL maintainer="youngk"
LABEL email="784253179@163.com"

RUN echo "Asia/Shanghai" > /etc/timezone


RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list \
    && mkdir /www/ \
    && chmod -R 755 /www/